### ISSUE TITLE
pi pico w times out when on the robotics board

### ISSUE THREAD

**Issue by ghost** [KitronikLtd/Kitronik-Pico-Robotics-Board-MicroPython#8]
I'm using a pi pico w to connect to a laptop using the sockets module. This works when the pico is on its own, but the connection times out when connected to the robotics board. I've also noticed connecting to wifi also takes longer. I'm powering both the board (4.8v) and the pico (via the laptop). Any ways to remedy this?

**Comment by JackAtKitronik** [comment]
Hi,

Thanks for your message and I am sorry to hear you are having an issue with the board. It is an issue we are aware can crop up and are working to resolve for our customers as quickly as possible. The regulator on the Pico board, whilst notably above specification for normal Pico use, runs into difficulties when trying to boost the WiFi to achieve connection as the current spike causes the regulator to kick in to protect the circuit. Unfortunately this board was created before the Pico W came out and so hadn't taken into account the current spike caused by the WiFi chip.

We are currently in the process of upgrading and changing the regulator to one that can handle the additional current when connecting. We are hoping that this can be done within the next few weeks.

In the meantime if you power the Pico separately from a USB during the connection period that can act as a work around in the short term for you.

When powering via USB, if you are still having issues try moving the Pico W closer to the access point you are connecting to. The range on the Pico W can be reduced when it is placed on to another board.

Feel free to send us an email if you'd like more help with this issue: [admin@kitronik.co.uk](mailto:admin@kitronik.co.uk)

Apologies again for the inconvenience caused.
